###
# Initialization

###
# @name Initialize
POST https://localhost:7108/TextGeneration/Initialize
Content-Type: application/json

{
  
}

###
# Inference

###
# @name TextGeneration
POST https://localhost:7108/TextGeneration/GenerateText
Content-Type: application/json

{
  "CallType": 1,
  "InputText": "If you could relate to one fictional character, who would it be?",
  "Temperature": 1.0,
  "TopK": 0,
  "TopP": 0.69,
  "RepetitionPenalty": 1.0,
  "MaxNewTokens": 400
}

###
# Model Swap

###
# @name SwapModel
POST https://localhost:7108/TextGeneration/SwapModel
Content-Type: application/json

{
  
}