###
# Initialization

###
# @name Initialize
POST https://localhost:7108/TextGeneration/Initialize
Content-Type: application/json

{
  
}

###
# Inference

###
# @name TextGeneration
POST https://localhost:7108/TextGeneration/GenerateText
Content-Type: application/json

{
  "InputText": "If you could relate to one fictional character, who would it be?",
  "CallType": 1
}

###
# Model Swap

###
# @name SwapModel
POST https://localhost:7108/TextGeneration/SwapModel
Content-Type: application/json

{
  
}